/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bcfapi);
  }
}(this, function(expect, Bcfapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bcfapi.CommentEventGET();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CommentEventGET', function() {
    it('should create an instance of CommentEventGET', function() {
      // uncomment below and update the code to test CommentEventGET
      //var instane = new Bcfapi.CommentEventGET();
      //expect(instance).to.be.a(Bcfapi.CommentEventGET);
    });

    it('should have the property commentGuid (base name: "comment_guid")', function() {
      // uncomment below and update the code to test the property commentGuid
      //var instane = new Bcfapi.CommentEventGET();
      //expect(instance).to.be();
    });

    it('should have the property topicGuid (base name: "topic_guid")', function() {
      // uncomment below and update the code to test the property topicGuid
      //var instane = new Bcfapi.CommentEventGET();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new Bcfapi.CommentEventGET();
      //expect(instance).to.be();
    });

    it('should have the property author (base name: "author")', function() {
      // uncomment below and update the code to test the property author
      //var instane = new Bcfapi.CommentEventGET();
      //expect(instance).to.be();
    });

    it('should have the property actions (base name: "actions")', function() {
      // uncomment below and update the code to test the property actions
      //var instane = new Bcfapi.CommentEventGET();
      //expect(instance).to.be();
    });

  });

}));
