/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bcfapi);
  }
}(this, function(expect, Bcfapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bcfapi.ExtensionsGET();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExtensionsGET', function() {
    it('should create an instance of ExtensionsGET', function() {
      // uncomment below and update the code to test ExtensionsGET
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be.a(Bcfapi.ExtensionsGET);
    });

    it('should have the property topicType (base name: "topic_type")', function() {
      // uncomment below and update the code to test the property topicType
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property topicStatus (base name: "topic_status")', function() {
      // uncomment below and update the code to test the property topicStatus
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property topicLabel (base name: "topic_label")', function() {
      // uncomment below and update the code to test the property topicLabel
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property snippetType (base name: "snippet_type")', function() {
      // uncomment below and update the code to test the property snippetType
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property userIdType (base name: "user_id_type")', function() {
      // uncomment below and update the code to test the property userIdType
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property stage (base name: "stage")', function() {
      // uncomment below and update the code to test the property stage
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property topicActions (base name: "topic_actions")', function() {
      // uncomment below and update the code to test the property topicActions
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property projectActions (base name: "project_actions")', function() {
      // uncomment below and update the code to test the property projectActions
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

    it('should have the property commentActions (base name: "comment_actions")', function() {
      // uncomment below and update the code to test the property commentActions
      //var instane = new Bcfapi.ExtensionsGET();
      //expect(instance).to.be();
    });

  });

}));
