/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bcfapi);
  }
}(this, function(expect, Bcfapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bcfapi.ViewpointGET();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ViewpointGET', function() {
    it('should create an instance of ViewpointGET', function() {
      // uncomment below and update the code to test ViewpointGET
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be.a(Bcfapi.ViewpointGET);
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property orthogonalCamera (base name: "orthogonal_camera")', function() {
      // uncomment below and update the code to test the property orthogonalCamera
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property perspectiveCamera (base name: "perspective_camera")', function() {
      // uncomment below and update the code to test the property perspectiveCamera
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property lines (base name: "lines")', function() {
      // uncomment below and update the code to test the property lines
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property clippingPlanes (base name: "clipping_planes")', function() {
      // uncomment below and update the code to test the property clippingPlanes
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property bitmaps (base name: "bitmaps")', function() {
      // uncomment below and update the code to test the property bitmaps
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

    it('should have the property snapshot (base name: "snapshot")', function() {
      // uncomment below and update the code to test the property snapshot
      //var instane = new Bcfapi.ViewpointGET();
      //expect(instance).to.be();
    });

  });

}));
