<?php
/**
 * AuthGETTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuthGETTest Class Doc Comment
 *
 * @category    Class */
// * @description AuthGET
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthGETTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuthGET"
     */
    public function testAuthGET()
    {
    }

    /**
     * Test attribute "oauth2_auth_url"
     */
    public function testPropertyOauth2AuthUrl()
    {
    }

    /**
     * Test attribute "oauth2_token_url"
     */
    public function testPropertyOauth2TokenUrl()
    {
    }

    /**
     * Test attribute "oauth2_dynamic_client_reg_url"
     */
    public function testPropertyOauth2DynamicClientRegUrl()
    {
    }

    /**
     * Test attribute "http_basic_supported"
     */
    public function testPropertyHttpBasicSupported()
    {
    }

    /**
     * Test attribute "supported_oauth2_flows"
     */
    public function testPropertySupportedOauth2Flows()
    {
    }
}
