<?php
/**
 * ExtensionsGETTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ExtensionsGETTest Class Doc Comment
 *
 * @category    Class */
// * @description ExtensionsGET
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExtensionsGETTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExtensionsGET"
     */
    public function testExtensionsGET()
    {
    }

    /**
     * Test attribute "topic_type"
     */
    public function testPropertyTopicType()
    {
    }

    /**
     * Test attribute "topic_status"
     */
    public function testPropertyTopicStatus()
    {
    }

    /**
     * Test attribute "topic_label"
     */
    public function testPropertyTopicLabel()
    {
    }

    /**
     * Test attribute "snippet_type"
     */
    public function testPropertySnippetType()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "user_id_type"
     */
    public function testPropertyUserIdType()
    {
    }

    /**
     * Test attribute "stage"
     */
    public function testPropertyStage()
    {
    }

    /**
     * Test attribute "topic_actions"
     */
    public function testPropertyTopicActions()
    {
    }

    /**
     * Test attribute "project_actions"
     */
    public function testPropertyProjectActions()
    {
    }

    /**
     * Test attribute "comment_actions"
     */
    public function testPropertyCommentActions()
    {
    }
}
