<?php
/**
 * OrthogonalCameraTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrthogonalCameraTest Class Doc Comment
 *
 * @category    Class */
// * @description OrthogonalCamera
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrthogonalCameraTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrthogonalCamera"
     */
    public function testOrthogonalCamera()
    {
    }

    /**
     * Test attribute "camera_view_point"
     */
    public function testPropertyCameraViewPoint()
    {
    }

    /**
     * Test attribute "camera_direction"
     */
    public function testPropertyCameraDirection()
    {
    }

    /**
     * Test attribute "camera_up_vector"
     */
    public function testPropertyCameraUpVector()
    {
    }

    /**
     * Test attribute "view_to_world_scale"
     */
    public function testPropertyViewToWorldScale()
    {
    }
}
