/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthGET model module.
* @module model/AuthGET
* @version 1.0.0
*/
export default class AuthGET {
    /**
    * Constructs a new <code>AuthGET</code>.
    * @alias module:model/AuthGET
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthGET</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthGET} obj Optional instance to populate.
    * @return {module:model/AuthGET} The populated <code>AuthGET</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthGET();

            
            
            

            if (data.hasOwnProperty('oauth2_auth_url')) {
                obj['oauth2_auth_url'] = ApiClient.convertToType(data['oauth2_auth_url'], 'String');
            }
            if (data.hasOwnProperty('oauth2_token_url')) {
                obj['oauth2_token_url'] = ApiClient.convertToType(data['oauth2_token_url'], 'String');
            }
            if (data.hasOwnProperty('oauth2_dynamic_client_reg_url')) {
                obj['oauth2_dynamic_client_reg_url'] = ApiClient.convertToType(data['oauth2_dynamic_client_reg_url'], 'String');
            }
            if (data.hasOwnProperty('http_basic_supported')) {
                obj['http_basic_supported'] = ApiClient.convertToType(data['http_basic_supported'], 'Boolean');
            }
            if (data.hasOwnProperty('supported_oauth2_flows')) {
                obj['supported_oauth2_flows'] = ApiClient.convertToType(data['supported_oauth2_flows'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} oauth2_auth_url
    */
    oauth2_auth_url = undefined;
    /**
    * @member {String} oauth2_token_url
    */
    oauth2_token_url = undefined;
    /**
    * @member {String} oauth2_dynamic_client_reg_url
    */
    oauth2_dynamic_client_reg_url = undefined;
    /**
    * @member {Boolean} http_basic_supported
    */
    http_basic_supported = undefined;
    /**
    * @member {Array.<String>} supported_oauth2_flows
    */
    supported_oauth2_flows = undefined;








}


