/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Authorization model module.
* @module model/Authorization
* @version 1.0.0
*/
export default class Authorization {
    /**
    * Constructs a new <code>Authorization</code>.
    * @alias module:model/Authorization
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Authorization</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Authorization} obj Optional instance to populate.
    * @return {module:model/Authorization} The populated <code>Authorization</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Authorization();

            
            
            

        }
        return obj;
    }









}


