/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CommentActions from './CommentActions';





/**
* The CommentGETAuthorization model module.
* @module model/CommentGETAuthorization
* @version 1.0.0
*/
export default class CommentGETAuthorization {
    /**
    * Constructs a new <code>CommentGETAuthorization</code>.
    * @alias module:model/CommentGETAuthorization
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CommentGETAuthorization</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CommentGETAuthorization} obj Optional instance to populate.
    * @return {module:model/CommentGETAuthorization} The populated <code>CommentGETAuthorization</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommentGETAuthorization();

            
            
            

            if (data.hasOwnProperty('comment_actions')) {
                obj['comment_actions'] = CommentActions.constructFromObject(data['comment_actions']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/CommentActions} comment_actions
    */
    comment_actions = undefined;








}


