/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CommentGETAuthorization from './CommentGETAuthorization';





/**
* The CommentGET model module.
* @module model/CommentGET
* @version 1.0.0
*/
export default class CommentGET {
    /**
    * Constructs a new <code>CommentGET</code>.
    * @alias module:model/CommentGET
    * @class
    * @param guid {String} 
    * @param _date {String} 
    * @param author {String} 
    * @param comment {String} 
    * @param topicGuid {String} 
    */

    constructor(guid, _date, author, comment, topicGuid) {
        

        
        

        this['guid'] = guid;this['date'] = _date;this['author'] = author;this['comment'] = comment;this['topic_guid'] = topicGuid;

        
    }

    /**
    * Constructs a <code>CommentGET</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CommentGET} obj Optional instance to populate.
    * @return {module:model/CommentGET} The populated <code>CommentGET</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommentGET();

            
            
            

            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('topic_guid')) {
                obj['topic_guid'] = ApiClient.convertToType(data['topic_guid'], 'String');
            }
            if (data.hasOwnProperty('viewpoint_guid')) {
                obj['viewpoint_guid'] = ApiClient.convertToType(data['viewpoint_guid'], 'String');
            }
            if (data.hasOwnProperty('reply_to_comment_guid')) {
                obj['reply_to_comment_guid'] = ApiClient.convertToType(data['reply_to_comment_guid'], 'String');
            }
            if (data.hasOwnProperty('modified_date')) {
                obj['modified_date'] = ApiClient.convertToType(data['modified_date'], 'String');
            }
            if (data.hasOwnProperty('modified_author')) {
                obj['modified_author'] = ApiClient.convertToType(data['modified_author'], 'String');
            }
            if (data.hasOwnProperty('authorization')) {
                obj['authorization'] = CommentGETAuthorization.constructFromObject(data['authorization']);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    guid = undefined;
    /**
    * @member {String} date
    */
    date = undefined;
    /**
    * @member {String} author
    */
    author = undefined;
    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {String} topic_guid
    */
    topic_guid = undefined;
    /**
    * @member {String} viewpoint_guid
    */
    viewpoint_guid = undefined;
    /**
    * @member {String} reply_to_comment_guid
    */
    reply_to_comment_guid = undefined;
    /**
    * @member {String} modified_date
    */
    modified_date = undefined;
    /**
    * @member {String} modified_author
    */
    modified_author = undefined;
    /**
    * @member {module:model/CommentGETAuthorization} authorization
    */
    authorization = undefined;








}


