/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CommentPOST model module.
* @module model/CommentPOST
* @version 1.0.0
*/
export default class CommentPOST {
    /**
    * Constructs a new <code>CommentPOST</code>.
    * @alias module:model/CommentPOST
    * @class
    * @param comment {String} 
    */

    constructor(comment) {
        

        
        

        this['comment'] = comment;

        
    }

    /**
    * Constructs a <code>CommentPOST</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CommentPOST} obj Optional instance to populate.
    * @return {module:model/CommentPOST} The populated <code>CommentPOST</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommentPOST();

            
            
            

            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('viewpoint_guid')) {
                obj['viewpoint_guid'] = ApiClient.convertToType(data['viewpoint_guid'], 'String');
            }
            if (data.hasOwnProperty('reply_to_comment_guid')) {
                obj['reply_to_comment_guid'] = ApiClient.convertToType(data['reply_to_comment_guid'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {String} viewpoint_guid
    */
    viewpoint_guid = undefined;
    /**
    * @member {String} reply_to_comment_guid
    */
    reply_to_comment_guid = undefined;








}


