/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Coloring from './Coloring';
import ComponentList from './ComponentList';
import Visibility from './Visibility';





/**
* The Components model module.
* @module model/Components
* @version 1.0.0
*/
export default class Components {
    /**
    * Constructs a new <code>Components</code>.
    * @alias module:model/Components
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Components</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Components} obj Optional instance to populate.
    * @return {module:model/Components} The populated <code>Components</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Components();

            
            
            

            if (data.hasOwnProperty('selection')) {
                obj['selection'] = ComponentList.constructFromObject(data['selection']);
            }
            if (data.hasOwnProperty('coloring')) {
                obj['coloring'] = ApiClient.convertToType(data['coloring'], [Coloring]);
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = Visibility.constructFromObject(data['visibility']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ComponentList} selection
    */
    selection = undefined;
    /**
    * @member {Array.<module:model/Coloring>} coloring
    */
    coloring = undefined;
    /**
    * @member {module:model/Visibility} visibility
    */
    visibility = undefined;








}


