/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DynRegClientGET model module.
* @module model/DynRegClientGET
* @version 1.0.0
*/
export default class DynRegClientGET {
    /**
    * Constructs a new <code>DynRegClientGET</code>.
    * Dynamic Client Meta Data
    * @alias module:model/DynRegClientGET
    * @class
    * @param clientId {String} 
    * @param clientSecret {String} 
    */

    constructor(clientId, clientSecret) {
        

        
        

        this['client_id'] = clientId;this['client_secret'] = clientSecret;

        
    }

    /**
    * Constructs a <code>DynRegClientGET</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DynRegClientGET} obj Optional instance to populate.
    * @return {module:model/DynRegClientGET} The populated <code>DynRegClientGET</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DynRegClientGET();

            
            
            

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} client_id
    */
    client_id = undefined;
    /**
    * @member {String} client_secret
    */
    client_secret = undefined;








}


