/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CommentActions from './CommentActions';
import ProjectActions from './ProjectActions';
import TopicActions from './TopicActions';





/**
* The ExtensionsGET model module.
* @module model/ExtensionsGET
* @version 1.0.0
*/
export default class ExtensionsGET {
    /**
    * Constructs a new <code>ExtensionsGET</code>.
    * @alias module:model/ExtensionsGET
    * @class
    * @param topicType {Array.<String>} 
    * @param topicStatus {Array.<String>} 
    * @param topicLabel {Array.<String>} 
    * @param snippetType {Array.<String>} 
    * @param priority {Array.<String>} 
    * @param userIdType {Array.<String>} 
    * @param stage {Array.<String>} 
    */

    constructor(topicType, topicStatus, topicLabel, snippetType, priority, userIdType, stage) {
        

        
        

        this['topic_type'] = topicType;this['topic_status'] = topicStatus;this['topic_label'] = topicLabel;this['snippet_type'] = snippetType;this['priority'] = priority;this['user_id_type'] = userIdType;this['stage'] = stage;

        
    }

    /**
    * Constructs a <code>ExtensionsGET</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ExtensionsGET} obj Optional instance to populate.
    * @return {module:model/ExtensionsGET} The populated <code>ExtensionsGET</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtensionsGET();

            
            
            

            if (data.hasOwnProperty('topic_type')) {
                obj['topic_type'] = ApiClient.convertToType(data['topic_type'], ['String']);
            }
            if (data.hasOwnProperty('topic_status')) {
                obj['topic_status'] = ApiClient.convertToType(data['topic_status'], ['String']);
            }
            if (data.hasOwnProperty('topic_label')) {
                obj['topic_label'] = ApiClient.convertToType(data['topic_label'], ['String']);
            }
            if (data.hasOwnProperty('snippet_type')) {
                obj['snippet_type'] = ApiClient.convertToType(data['snippet_type'], ['String']);
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], ['String']);
            }
            if (data.hasOwnProperty('user_id_type')) {
                obj['user_id_type'] = ApiClient.convertToType(data['user_id_type'], ['String']);
            }
            if (data.hasOwnProperty('stage')) {
                obj['stage'] = ApiClient.convertToType(data['stage'], ['String']);
            }
            if (data.hasOwnProperty('topic_actions')) {
                obj['topic_actions'] = TopicActions.constructFromObject(data['topic_actions']);
            }
            if (data.hasOwnProperty('project_actions')) {
                obj['project_actions'] = ProjectActions.constructFromObject(data['project_actions']);
            }
            if (data.hasOwnProperty('comment_actions')) {
                obj['comment_actions'] = CommentActions.constructFromObject(data['comment_actions']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} topic_type
    */
    topic_type = undefined;
    /**
    * @member {Array.<String>} topic_status
    */
    topic_status = undefined;
    /**
    * @member {Array.<String>} topic_label
    */
    topic_label = undefined;
    /**
    * @member {Array.<String>} snippet_type
    */
    snippet_type = undefined;
    /**
    * @member {Array.<String>} priority
    */
    priority = undefined;
    /**
    * @member {Array.<String>} user_id_type
    */
    user_id_type = undefined;
    /**
    * @member {Array.<String>} stage
    */
    stage = undefined;
    /**
    * @member {module:model/TopicActions} topic_actions
    */
    topic_actions = undefined;
    /**
    * @member {module:model/ProjectActions} project_actions
    */
    project_actions = undefined;
    /**
    * @member {module:model/CommentActions} comment_actions
    */
    comment_actions = undefined;








}


