/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ProjectActions model module.
* @module model/ProjectActions
* @version 1.0.0
*/
export default class ProjectActions extends Array {
    /**
    * Constructs a new <code>ProjectActions</code>.
    * @alias module:model/ProjectActions
    * @class
    * @extends Array
    */

    constructor() {
        
        super();
        

        
        

        

        return this;
    }

    /**
    * Constructs a <code>ProjectActions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProjectActions} obj Optional instance to populate.
    * @return {module:model/ProjectActions} The populated <code>ProjectActions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectActions();

            ApiClient.constructFromObject(data, obj, 'String');

            
            

        }
        return obj;
    }









}


