/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ProjectActions from './ProjectActions';





/**
* The ProjectGETAuthorization model module.
* @module model/ProjectGETAuthorization
* @version 1.0.0
*/
export default class ProjectGETAuthorization {
    /**
    * Constructs a new <code>ProjectGETAuthorization</code>.
    * @alias module:model/ProjectGETAuthorization
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ProjectGETAuthorization</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProjectGETAuthorization} obj Optional instance to populate.
    * @return {module:model/ProjectGETAuthorization} The populated <code>ProjectGETAuthorization</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectGETAuthorization();

            
            
            

            if (data.hasOwnProperty('project_actions')) {
                obj['project_actions'] = ProjectActions.constructFromObject(data['project_actions']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ProjectActions} project_actions
    */
    project_actions = undefined;








}


