/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RelatedTopicGET model module.
* @module model/RelatedTopicGET
* @version 1.0.0
*/
export default class RelatedTopicGET {
    /**
    * Constructs a new <code>RelatedTopicGET</code>.
    * Schema for single related topic GET, BCF REST API.
    * @alias module:model/RelatedTopicGET
    * @class
    * @param relatedTopicGuid {String} 
    */

    constructor(relatedTopicGuid) {
        

        
        

        this['related_topic_guid'] = relatedTopicGuid;

        
    }

    /**
    * Constructs a <code>RelatedTopicGET</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RelatedTopicGET} obj Optional instance to populate.
    * @return {module:model/RelatedTopicGET} The populated <code>RelatedTopicGET</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelatedTopicGET();

            
            
            

            if (data.hasOwnProperty('related_topic_guid')) {
                obj['related_topic_guid'] = ApiClient.convertToType(data['related_topic_guid'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} related_topic_guid
    */
    related_topic_guid = undefined;








}


