/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import BimSnippet from './BimSnippet';





/**
* The TopicPUT model module.
* @module model/TopicPUT
* @version 1.0.0
*/
export default class TopicPUT {
    /**
    * Constructs a new <code>TopicPUT</code>.
    * @alias module:model/TopicPUT
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TopicPUT</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TopicPUT} obj Optional instance to populate.
    * @return {module:model/TopicPUT} The populated <code>TopicPUT</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicPUT();

            
            
            

            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('topic_type')) {
                obj['topic_type'] = ApiClient.convertToType(data['topic_type'], 'String');
            }
            if (data.hasOwnProperty('topic_status')) {
                obj['topic_status'] = ApiClient.convertToType(data['topic_status'], 'String');
            }
            if (data.hasOwnProperty('reference_links')) {
                obj['reference_links'] = ApiClient.convertToType(data['reference_links'], ['String']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
            if (data.hasOwnProperty('creation_date')) {
                obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'String');
            }
            if (data.hasOwnProperty('creation_author')) {
                obj['creation_author'] = ApiClient.convertToType(data['creation_author'], 'String');
            }
            if (data.hasOwnProperty('modified_date')) {
                obj['modified_date'] = ApiClient.convertToType(data['modified_date'], 'String');
            }
            if (data.hasOwnProperty('modified_author')) {
                obj['modified_author'] = ApiClient.convertToType(data['modified_author'], 'String');
            }
            if (data.hasOwnProperty('assigned_to')) {
                obj['assigned_to'] = ApiClient.convertToType(data['assigned_to'], 'String');
            }
            if (data.hasOwnProperty('stage')) {
                obj['stage'] = ApiClient.convertToType(data['stage'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('bim_snippet')) {
                obj['bim_snippet'] = BimSnippet.constructFromObject(data['bim_snippet']);
            }
            if (data.hasOwnProperty('due_date')) {
                obj['due_date'] = ApiClient.convertToType(data['due_date'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    guid = undefined;
    /**
    * @member {String} topic_type
    */
    topic_type = undefined;
    /**
    * @member {String} topic_status
    */
    topic_status = undefined;
    /**
    * @member {Array.<String>} reference_links
    */
    reference_links = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} priority
    */
    priority = undefined;
    /**
    * @member {Number} index
    */
    index = undefined;
    /**
    * @member {Array.<String>} labels
    */
    labels = undefined;
    /**
    * @member {String} creation_date
    */
    creation_date = undefined;
    /**
    * @member {String} creation_author
    */
    creation_author = undefined;
    /**
    * @member {String} modified_date
    */
    modified_date = undefined;
    /**
    * @member {String} modified_author
    */
    modified_author = undefined;
    /**
    * @member {String} assigned_to
    */
    assigned_to = undefined;
    /**
    * @member {String} stage
    */
    stage = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {module:model/BimSnippet} bim_snippet
    */
    bim_snippet = undefined;
    /**
    * @member {String} due_date
    */
    due_date = undefined;








}


