/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TopicActions from './TopicActions';





/**
* The TopicGETAuthorization model module.
* @module model/TopicGETAuthorization
* @version 1.0.0
*/
export default class TopicGETAuthorization {
    /**
    * Constructs a new <code>TopicGETAuthorization</code>.
    * @alias module:model/TopicGETAuthorization
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TopicGETAuthorization</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TopicGETAuthorization} obj Optional instance to populate.
    * @return {module:model/TopicGETAuthorization} The populated <code>TopicGETAuthorization</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicGETAuthorization();

            
            
            

            if (data.hasOwnProperty('topic_actions')) {
                obj['topic_actions'] = TopicActions.constructFromObject(data['topic_actions']);
            }
            if (data.hasOwnProperty('topic_status')) {
                obj['topic_status'] = ApiClient.convertToType(data['topic_status'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/TopicActions} topic_actions
    */
    topic_actions = undefined;
    /**
    * @member {Array.<String>} topic_status
    */
    topic_status = undefined;








}


