/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ViewSetupHints model module.
* @module model/ViewSetupHints
* @version 1.0.0
*/
export default class ViewSetupHints {
    /**
    * Constructs a new <code>ViewSetupHints</code>.
    * @alias module:model/ViewSetupHints
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ViewSetupHints</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ViewSetupHints} obj Optional instance to populate.
    * @return {module:model/ViewSetupHints} The populated <code>ViewSetupHints</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ViewSetupHints();

            
            
            

            if (data.hasOwnProperty('spaces_visible')) {
                obj['spaces_visible'] = ApiClient.convertToType(data['spaces_visible'], 'Boolean');
            }
            if (data.hasOwnProperty('space_boundaries_visible')) {
                obj['space_boundaries_visible'] = ApiClient.convertToType(data['space_boundaries_visible'], 'Boolean');
            }
            if (data.hasOwnProperty('openings_visible')) {
                obj['openings_visible'] = ApiClient.convertToType(data['openings_visible'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} spaces_visible
    * @default false
    */
    spaces_visible = false;
    /**
    * @member {Boolean} space_boundaries_visible
    * @default false
    */
    space_boundaries_visible = false;
    /**
    * @member {Boolean} openings_visible
    * @default false
    */
    openings_visible = false;








}


