<?php
/**
 * CommentGET
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CommentGET Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommentGET implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'comment_GET';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'guid' => 'string',
        'date' => 'string',
        'author' => 'string',
        'comment' => 'string',
        'topic_guid' => 'string',
        'viewpoint_guid' => 'string',
        'reply_to_comment_guid' => 'string',
        'modified_date' => 'string',
        'modified_author' => 'string',
        'authorization' => '\Swagger\Client\Model\CommentGETAuthorization'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'guid' => null,
        'date' => null,
        'author' => null,
        'comment' => null,
        'topic_guid' => null,
        'viewpoint_guid' => null,
        'reply_to_comment_guid' => null,
        'modified_date' => null,
        'modified_author' => null,
        'authorization' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'guid' => 'guid',
        'date' => 'date',
        'author' => 'author',
        'comment' => 'comment',
        'topic_guid' => 'topic_guid',
        'viewpoint_guid' => 'viewpoint_guid',
        'reply_to_comment_guid' => 'reply_to_comment_guid',
        'modified_date' => 'modified_date',
        'modified_author' => 'modified_author',
        'authorization' => 'authorization'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'guid' => 'setGuid',
        'date' => 'setDate',
        'author' => 'setAuthor',
        'comment' => 'setComment',
        'topic_guid' => 'setTopicGuid',
        'viewpoint_guid' => 'setViewpointGuid',
        'reply_to_comment_guid' => 'setReplyToCommentGuid',
        'modified_date' => 'setModifiedDate',
        'modified_author' => 'setModifiedAuthor',
        'authorization' => 'setAuthorization'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'guid' => 'getGuid',
        'date' => 'getDate',
        'author' => 'getAuthor',
        'comment' => 'getComment',
        'topic_guid' => 'getTopicGuid',
        'viewpoint_guid' => 'getViewpointGuid',
        'reply_to_comment_guid' => 'getReplyToCommentGuid',
        'modified_date' => 'getModifiedDate',
        'modified_author' => 'getModifiedAuthor',
        'authorization' => 'getAuthorization'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['guid'] = isset($data['guid']) ? $data['guid'] : null;
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['author'] = isset($data['author']) ? $data['author'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['topic_guid'] = isset($data['topic_guid']) ? $data['topic_guid'] : null;
        $this->container['viewpoint_guid'] = isset($data['viewpoint_guid']) ? $data['viewpoint_guid'] : null;
        $this->container['reply_to_comment_guid'] = isset($data['reply_to_comment_guid']) ? $data['reply_to_comment_guid'] : null;
        $this->container['modified_date'] = isset($data['modified_date']) ? $data['modified_date'] : null;
        $this->container['modified_author'] = isset($data['modified_author']) ? $data['modified_author'] : null;
        $this->container['authorization'] = isset($data['authorization']) ? $data['authorization'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['guid'] === null) {
            $invalidProperties[] = "'guid' can't be null";
        }
        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['author'] === null) {
            $invalidProperties[] = "'author' can't be null";
        }
        if ($this->container['comment'] === null) {
            $invalidProperties[] = "'comment' can't be null";
        }
        if ($this->container['topic_guid'] === null) {
            $invalidProperties[] = "'topic_guid' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['guid'] === null) {
            return false;
        }
        if ($this->container['date'] === null) {
            return false;
        }
        if ($this->container['author'] === null) {
            return false;
        }
        if ($this->container['comment'] === null) {
            return false;
        }
        if ($this->container['topic_guid'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets guid
     *
     * @return string
     */
    public function getGuid()
    {
        return $this->container['guid'];
    }

    /**
     * Sets guid
     *
     * @param string $guid guid
     *
     * @return $this
     */
    public function setGuid($guid)
    {
        $this->container['guid'] = $guid;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string $date date
     *
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param string $author author
     *
     * @return $this
     */
    public function setAuthor($author)
    {
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string $comment comment
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets topic_guid
     *
     * @return string
     */
    public function getTopicGuid()
    {
        return $this->container['topic_guid'];
    }

    /**
     * Sets topic_guid
     *
     * @param string $topic_guid topic_guid
     *
     * @return $this
     */
    public function setTopicGuid($topic_guid)
    {
        $this->container['topic_guid'] = $topic_guid;

        return $this;
    }

    /**
     * Gets viewpoint_guid
     *
     * @return string
     */
    public function getViewpointGuid()
    {
        return $this->container['viewpoint_guid'];
    }

    /**
     * Sets viewpoint_guid
     *
     * @param string $viewpoint_guid viewpoint_guid
     *
     * @return $this
     */
    public function setViewpointGuid($viewpoint_guid)
    {
        $this->container['viewpoint_guid'] = $viewpoint_guid;

        return $this;
    }

    /**
     * Gets reply_to_comment_guid
     *
     * @return string
     */
    public function getReplyToCommentGuid()
    {
        return $this->container['reply_to_comment_guid'];
    }

    /**
     * Sets reply_to_comment_guid
     *
     * @param string $reply_to_comment_guid reply_to_comment_guid
     *
     * @return $this
     */
    public function setReplyToCommentGuid($reply_to_comment_guid)
    {
        $this->container['reply_to_comment_guid'] = $reply_to_comment_guid;

        return $this;
    }

    /**
     * Gets modified_date
     *
     * @return string
     */
    public function getModifiedDate()
    {
        return $this->container['modified_date'];
    }

    /**
     * Sets modified_date
     *
     * @param string $modified_date modified_date
     *
     * @return $this
     */
    public function setModifiedDate($modified_date)
    {
        $this->container['modified_date'] = $modified_date;

        return $this;
    }

    /**
     * Gets modified_author
     *
     * @return string
     */
    public function getModifiedAuthor()
    {
        return $this->container['modified_author'];
    }

    /**
     * Sets modified_author
     *
     * @param string $modified_author modified_author
     *
     * @return $this
     */
    public function setModifiedAuthor($modified_author)
    {
        $this->container['modified_author'] = $modified_author;

        return $this;
    }

    /**
     * Gets authorization
     *
     * @return \Swagger\Client\Model\CommentGETAuthorization
     */
    public function getAuthorization()
    {
        return $this->container['authorization'];
    }

    /**
     * Sets authorization
     *
     * @param \Swagger\Client\Model\CommentGETAuthorization $authorization authorization
     *
     * @return $this
     */
    public function setAuthorization($authorization)
    {
        $this->container['authorization'] = $authorization;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

