<?php
/**
 * PerspectiveCamera
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PerspectiveCamera Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PerspectiveCamera implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'perspective_camera';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'camera_view_point' => '\Swagger\Client\Model\Point',
        'camera_direction' => '\Swagger\Client\Model\Direction',
        'camera_up_vector' => '\Swagger\Client\Model\Direction',
        'field_of_view' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'camera_view_point' => null,
        'camera_direction' => null,
        'camera_up_vector' => null,
        'field_of_view' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'camera_view_point' => 'camera_view_point',
        'camera_direction' => 'camera_direction',
        'camera_up_vector' => 'camera_up_vector',
        'field_of_view' => 'field_of_view'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'camera_view_point' => 'setCameraViewPoint',
        'camera_direction' => 'setCameraDirection',
        'camera_up_vector' => 'setCameraUpVector',
        'field_of_view' => 'setFieldOfView'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'camera_view_point' => 'getCameraViewPoint',
        'camera_direction' => 'getCameraDirection',
        'camera_up_vector' => 'getCameraUpVector',
        'field_of_view' => 'getFieldOfView'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['camera_view_point'] = isset($data['camera_view_point']) ? $data['camera_view_point'] : null;
        $this->container['camera_direction'] = isset($data['camera_direction']) ? $data['camera_direction'] : null;
        $this->container['camera_up_vector'] = isset($data['camera_up_vector']) ? $data['camera_up_vector'] : null;
        $this->container['field_of_view'] = isset($data['field_of_view']) ? $data['field_of_view'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets camera_view_point
     *
     * @return \Swagger\Client\Model\Point
     */
    public function getCameraViewPoint()
    {
        return $this->container['camera_view_point'];
    }

    /**
     * Sets camera_view_point
     *
     * @param \Swagger\Client\Model\Point $camera_view_point camera_view_point
     *
     * @return $this
     */
    public function setCameraViewPoint($camera_view_point)
    {
        $this->container['camera_view_point'] = $camera_view_point;

        return $this;
    }

    /**
     * Gets camera_direction
     *
     * @return \Swagger\Client\Model\Direction
     */
    public function getCameraDirection()
    {
        return $this->container['camera_direction'];
    }

    /**
     * Sets camera_direction
     *
     * @param \Swagger\Client\Model\Direction $camera_direction camera_direction
     *
     * @return $this
     */
    public function setCameraDirection($camera_direction)
    {
        $this->container['camera_direction'] = $camera_direction;

        return $this;
    }

    /**
     * Gets camera_up_vector
     *
     * @return \Swagger\Client\Model\Direction
     */
    public function getCameraUpVector()
    {
        return $this->container['camera_up_vector'];
    }

    /**
     * Sets camera_up_vector
     *
     * @param \Swagger\Client\Model\Direction $camera_up_vector camera_up_vector
     *
     * @return $this
     */
    public function setCameraUpVector($camera_up_vector)
    {
        $this->container['camera_up_vector'] = $camera_up_vector;

        return $this;
    }

    /**
     * Gets field_of_view
     *
     * @return float
     */
    public function getFieldOfView()
    {
        return $this->container['field_of_view'];
    }

    /**
     * Sets field_of_view
     *
     * @param float $field_of_view field_of_view
     *
     * @return $this
     */
    public function setFieldOfView($field_of_view)
    {
        $this->container['field_of_view'] = $field_of_view;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

