/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bcfapi);
  }
}(this, function(expect, Bcfapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bcfapi.CommentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CommentApi', function() {
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidDelete', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidDelete successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidDelete
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidPut', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidPut successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidPut
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidCommentsGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidCommentsGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidCommentsGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidCommentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidCommentsPost', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidCommentsPost successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidCommentsPost
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidCommentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
