/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bcfapi);
  }
}(this, function(expect, Bcfapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bcfapi.ViewpointApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ViewpointApi', function() {
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsPost', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsPost successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsPost
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidBitmapsBitmapGuidGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidBitmapsBitmapGuidGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidBitmapsBitmapGuidGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidBitmapsBitmapGuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidColoringGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidColoringGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidColoringGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidColoringGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSelectionGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSelectionGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSelectionGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSelectionGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSnapshotGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSnapshotGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSnapshotGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidSnapshotGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidVisibilityGet', function() {
      it('should call bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidVisibilityGet successfully', function(done) {
        //uncomment below and update the code to test bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidVisibilityGet
        //instance.bcfVersionProjectsProjectIdTopicsTopicGuidViewpointsViewpointGuidVisibilityGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
