/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommentEventGET from '../model/CommentEventGET';

/**
* CommentEvents service.
* @module api/CommentEventsApi
* @version 1.0.0
*/
export default class CommentEventsApi {

    /**
    * Constructs a new CommentEventsApi. 
    * @alias module:api/CommentEventsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsCommentsEventsGet operation.
     * @callback module:api/CommentEventsApi~bcfVersionProjectsProjectIdTopicsCommentsEventsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CommentEventGET>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * RRetrieve a collection of comment events related to a project.
     * Retrieve a collection of comment events related to a project (default sort order is date).
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {module:api/CommentEventsApi~bcfVersionProjectsProjectIdTopicsCommentsEventsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CommentEventGET>}
     */
    bcfVersionProjectsProjectIdTopicsCommentsEventsGet(version, projectId, callback) {
      let postBody = null;

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsCommentsEventsGet");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsCommentsEventsGet");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CommentEventGET];

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/comments/events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGet operation.
     * @callback module:api/CommentEventsApi~bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CommentEventGET>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * RRetrieve a collection of comment events related to a project.
     * Retrieve a collection of comment events related to a project (default sort order is date).
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {String} topicGuid Topic guid
     * @param {String} commentGuid Comment guid
     * @param {module:api/CommentEventsApi~bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CommentEventGET>}
     */
    bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGet(version, projectId, topicGuid, commentGuid, callback) {
      let postBody = null;

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGet");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGet");
      }

      // verify the required parameter 'topicGuid' is set
      if (topicGuid === undefined || topicGuid === null) {
        throw new Error("Missing the required parameter 'topicGuid' when calling bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGet");
      }

      // verify the required parameter 'commentGuid' is set
      if (commentGuid === undefined || commentGuid === null) {
        throw new Error("Missing the required parameter 'commentGuid' when calling bcfVersionProjectsProjectIdTopicsTopicGuidCommentsCommentGuidEventsGet");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId,
        'topic_guid': topicGuid,
        'comment_guid': commentGuid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CommentEventGET];

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/{topic_guid}/comments/{comment_guid}/events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
