/**
 * BCFAPI
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommentGET from '../model/CommentGET';
import CommentPOST from '../model/CommentPOST';
import CommentPUT from '../model/CommentPUT';

/**
* Comment service.
* @module api/CommentApi
* @version 1.0.0
*/
export default class CommentApi {

    /**
    * Constructs a new CommentApi. 
    * @alias module:api/CommentApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsGuidCommentsGet operation.
     * @callback module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/CommentGET>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a collection of all comments related to a topic
     * Retrieve a collection of all comments related to a topic (default ordering is date).
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {String} guid Topic guid
     * @param {module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/CommentGET>}
     */
    bcfVersionProjectsProjectIdTopicsGuidCommentsGet(version, projectId, guid, callback) {
      let postBody = null;

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGet");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGet");
      }

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGet");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId,
        'guid': guid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [CommentGET];

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/{guid}/comments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete operation.
     * @callback module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a single comment.
     * Deletes a single comment. This operation is only possible when the server returns the delete flag in the Comment authorization.
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {String} guid Comment guid
     * @param {module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete(version, projectId, guid, callback) {
      let postBody = null;

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete");
      }

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId,
        'guid': guid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/{guid}/comments/{guid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet operation.
     * @callback module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CommentGET} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a collection of all comments related to a topic
     * Retrieve a collection of all comments related to a topic (default ordering is date).
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {String} guid Comment guid
     * @param {module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CommentGET}
     */
    bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet(version, projectId, guid, callback) {
      let postBody = null;

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet");
      }

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId,
        'guid': guid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CommentGET;

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/{guid}/comments/{guid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut operation.
     * @callback module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CommentGET} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a single comment
     * Update a single comment, description similar to POST. This operation is only possible when the server returns the update flag in the Comment authorization.
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {String} guid Comment guid
     * @param {Object} opts Optional parameters
     * @param {module:model/CommentPUT} opts.commentPUT 
     * @param {module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CommentGET}
     */
    bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut(version, projectId, guid, opts, callback) {
      opts = opts || {};
      let postBody = opts['commentPUT'];

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut");
      }

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId,
        'guid': guid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CommentGET;

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/{guid}/comments/{guid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bcfVersionProjectsProjectIdTopicsGuidCommentsPost operation.
     * @callback module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CommentGET} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new comment to a topic.
     * Add a new comment to a topic. This operation is only possible when the server returns the createComment flag in the Topic authorization.
     * @param {module:model/String} version BFC Version
     * @param {String} projectId Project ID
     * @param {String} guid Topic guid
     * @param {Object} opts Optional parameters
     * @param {module:model/CommentPOST} opts.commentPOST 
     * @param {module:api/CommentApi~bcfVersionProjectsProjectIdTopicsGuidCommentsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CommentGET}
     */
    bcfVersionProjectsProjectIdTopicsGuidCommentsPost(version, projectId, guid, opts, callback) {
      opts = opts || {};
      let postBody = opts['commentPOST'];

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsPost");
      }

      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsPost");
      }

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling bcfVersionProjectsProjectIdTopicsGuidCommentsPost");
      }


      let pathParams = {
        'version': version,
        'project_id': projectId,
        'guid': guid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CommentGET;

      return this.apiClient.callApi(
        '/bcf/{version}/projects/{project_id}/topics/{guid}/comments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
