<?php
/**
 * TopicApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TopicApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TopicApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGet
     *
     * Retrieve a collection of topics related to a project.
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsPost
     *
     * Add a new topic..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsPost()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsTopicGuidDelete
     *
     * Deletes a single topic..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsTopicGuidDelete()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsTopicGuidGet
     *
     * Retrieve a specific topic..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsTopicGuidGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsTopicGuidPut
     *
     * Modify a specific topic.
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsTopicGuidPut()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsTopicGuidSnippetGet
     *
     * Retrieves a topics BIM-Snippet as binary file..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsTopicGuidSnippetGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsTopicGuidSnippetPut
     *
     * Puts a new BIM Snippet binary file to a topic.
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsTopicGuidSnippetPut()
    {
    }
}
