<?php
/**
 * ViewpointApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ViewpointApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ViewpointApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bcfVersionProjectsGuidTopicsGuidViewpointsGuidBitmapsGuidGet
     *
     * Retrieve a specific viewpoints bitmap image file (png or jpg)..
     *
     */
    public function testBcfVersionProjectsGuidTopicsGuidViewpointsGuidBitmapsGuidGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsGuidTopicsGuidViewpointsGuidSnapshotGet
     *
     * Retrieve a viewpoints snapshot (png or jpg) as image file..
     *
     */
    public function testBcfVersionProjectsGuidTopicsGuidViewpointsGuidSnapshotGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGuidViewpointsGet
     *
     * Retrieve a collection of all viewpoints related to a topic..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGuidViewpointsGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGuidViewpointsGuidColoringGet
     *
     * Retrieve a collection of all colored components in a viewpoint..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGuidViewpointsGuidColoringGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGuidViewpointsGuidGet
     *
     * Retrieve a collection of all viewpoints related to a topic..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGuidViewpointsGuidGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGuidViewpointsGuidSelectionGet
     *
     * Retrieve a collection of all selected components in a viewpoint..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGuidViewpointsGuidSelectionGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGuidViewpointsGuidVisibilityGet
     *
     * Retrieve visibility of components in a viewpoint..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGuidViewpointsGuidVisibilityGet()
    {
    }

    /**
     * Test case for bcfVersionProjectsProjectIdTopicsGuidViewpointsPost
     *
     * Add a new viewpoint..
     *
     */
    public function testBcfVersionProjectsProjectIdTopicsGuidViewpointsPost()
    {
    }
}
