<?php
/**
 * CommentApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BCFAPI
 *
 * A BCF API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * CommentApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CommentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGet
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CommentGET[]
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGet($version, $project_id, $guid)
    {
        list($response) = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGetWithHttpInfo($version, $project_id, $guid);
        return $response;
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGetWithHttpInfo
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CommentGET[], HTTP status code, HTTP response headers (array of strings)
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGetWithHttpInfo($version, $project_id, $guid)
    {
        $returnType = '\Swagger\Client\Model\CommentGET[]';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGetRequest($version, $project_id, $guid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CommentGET[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGetAsync
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGetAsync($version, $project_id, $guid)
    {
        return $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGetAsyncWithHttpInfo($version, $project_id, $guid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGetAsyncWithHttpInfo
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGetAsyncWithHttpInfo($version, $project_id, $guid)
    {
        $returnType = '\Swagger\Client\Model\CommentGET[]';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGetRequest($version, $project_id, $guid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bcfVersionProjectsProjectIdTopicsGuidCommentsGet'
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bcfVersionProjectsProjectIdTopicsGuidCommentsGetRequest($version, $project_id, $guid)
    {
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGet'
            );
        }
        // verify the required parameter 'project_id' is set
        if ($project_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGet'
            );
        }
        // verify the required parameter 'guid' is set
        if ($guid === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guid when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGet'
            );
        }

        $resourcePath = '/bcf/{version}/projects/{project_id}/topics/{guid}/comments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($guid !== null) {
            $resourcePath = str_replace(
                '{' . 'guid' . '}',
                ObjectSerializer::toPathValue($guid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete
     *
     * Deletes a single comment.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete($version, $project_id, $guid)
    {
        $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteWithHttpInfo($version, $project_id, $guid);
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteWithHttpInfo
     *
     * Deletes a single comment.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteWithHttpInfo($version, $project_id, $guid)
    {
        $returnType = '';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteRequest($version, $project_id, $guid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteAsync
     *
     * Deletes a single comment.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteAsync($version, $project_id, $guid)
    {
        return $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteAsyncWithHttpInfo($version, $project_id, $guid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteAsyncWithHttpInfo
     *
     * Deletes a single comment.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteAsyncWithHttpInfo($version, $project_id, $guid)
    {
        $returnType = '';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteRequest($version, $project_id, $guid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete'
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDeleteRequest($version, $project_id, $guid)
    {
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete'
            );
        }
        // verify the required parameter 'project_id' is set
        if ($project_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete'
            );
        }
        // verify the required parameter 'guid' is set
        if ($guid === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guid when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidDelete'
            );
        }

        $resourcePath = '/bcf/{version}/projects/{project_id}/topics/{guid}/comments/{guid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($guid !== null) {
            $resourcePath = str_replace(
                '{' . 'guid' . '}',
                ObjectSerializer::toPathValue($guid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CommentGET
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet($version, $project_id, $guid)
    {
        list($response) = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetWithHttpInfo($version, $project_id, $guid);
        return $response;
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetWithHttpInfo
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CommentGET, HTTP status code, HTTP response headers (array of strings)
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetWithHttpInfo($version, $project_id, $guid)
    {
        $returnType = '\Swagger\Client\Model\CommentGET';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetRequest($version, $project_id, $guid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CommentGET',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetAsync
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetAsync($version, $project_id, $guid)
    {
        return $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetAsyncWithHttpInfo($version, $project_id, $guid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetAsyncWithHttpInfo
     *
     * Retrieve a collection of all comments related to a topic
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetAsyncWithHttpInfo($version, $project_id, $guid)
    {
        $returnType = '\Swagger\Client\Model\CommentGET';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetRequest($version, $project_id, $guid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet'
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGetRequest($version, $project_id, $guid)
    {
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet'
            );
        }
        // verify the required parameter 'project_id' is set
        if ($project_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet'
            );
        }
        // verify the required parameter 'guid' is set
        if ($guid === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guid when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidGet'
            );
        }

        $resourcePath = '/bcf/{version}/projects/{project_id}/topics/{guid}/comments/{guid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($guid !== null) {
            $resourcePath = str_replace(
                '{' . 'guid' . '}',
                ObjectSerializer::toPathValue($guid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut
     *
     * Update a single comment
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     * @param  \Swagger\Client\Model\CommentPUT $comment_put comment_put (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CommentGET
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut($version, $project_id, $guid, $comment_put = null)
    {
        list($response) = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutWithHttpInfo($version, $project_id, $guid, $comment_put);
        return $response;
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutWithHttpInfo
     *
     * Update a single comment
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     * @param  \Swagger\Client\Model\CommentPUT $comment_put (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CommentGET, HTTP status code, HTTP response headers (array of strings)
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutWithHttpInfo($version, $project_id, $guid, $comment_put = null)
    {
        $returnType = '\Swagger\Client\Model\CommentGET';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutRequest($version, $project_id, $guid, $comment_put);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CommentGET',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutAsync
     *
     * Update a single comment
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     * @param  \Swagger\Client\Model\CommentPUT $comment_put (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutAsync($version, $project_id, $guid, $comment_put = null)
    {
        return $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutAsyncWithHttpInfo($version, $project_id, $guid, $comment_put)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutAsyncWithHttpInfo
     *
     * Update a single comment
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     * @param  \Swagger\Client\Model\CommentPUT $comment_put (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutAsyncWithHttpInfo($version, $project_id, $guid, $comment_put = null)
    {
        $returnType = '\Swagger\Client\Model\CommentGET';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutRequest($version, $project_id, $guid, $comment_put);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut'
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Comment guid (required)
     * @param  \Swagger\Client\Model\CommentPUT $comment_put (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPutRequest($version, $project_id, $guid, $comment_put = null)
    {
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut'
            );
        }
        // verify the required parameter 'project_id' is set
        if ($project_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut'
            );
        }
        // verify the required parameter 'guid' is set
        if ($guid === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guid when calling bcfVersionProjectsProjectIdTopicsGuidCommentsGuidPut'
            );
        }

        $resourcePath = '/bcf/{version}/projects/{project_id}/topics/{guid}/comments/{guid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($guid !== null) {
            $resourcePath = str_replace(
                '{' . 'guid' . '}',
                ObjectSerializer::toPathValue($guid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($comment_put)) {
            $_tempBody = $comment_put;
        }

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsPost
     *
     * Add a new comment to a topic.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     * @param  \Swagger\Client\Model\CommentPOST $comment_post comment_post (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CommentGET
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsPost($version, $project_id, $guid, $comment_post = null)
    {
        list($response) = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsPostWithHttpInfo($version, $project_id, $guid, $comment_post);
        return $response;
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsPostWithHttpInfo
     *
     * Add a new comment to a topic.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     * @param  \Swagger\Client\Model\CommentPOST $comment_post (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CommentGET, HTTP status code, HTTP response headers (array of strings)
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsPostWithHttpInfo($version, $project_id, $guid, $comment_post = null)
    {
        $returnType = '\Swagger\Client\Model\CommentGET';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsPostRequest($version, $project_id, $guid, $comment_post);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse()->getBody()->getContents()
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CommentGET',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsPostAsync
     *
     * Add a new comment to a topic.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     * @param  \Swagger\Client\Model\CommentPOST $comment_post (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsPostAsync($version, $project_id, $guid, $comment_post = null)
    {
        return $this->bcfVersionProjectsProjectIdTopicsGuidCommentsPostAsyncWithHttpInfo($version, $project_id, $guid, $comment_post)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bcfVersionProjectsProjectIdTopicsGuidCommentsPostAsyncWithHttpInfo
     *
     * Add a new comment to a topic.
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     * @param  \Swagger\Client\Model\CommentPOST $comment_post (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bcfVersionProjectsProjectIdTopicsGuidCommentsPostAsyncWithHttpInfo($version, $project_id, $guid, $comment_post = null)
    {
        $returnType = '\Swagger\Client\Model\CommentGET';
        $request = $this->bcfVersionProjectsProjectIdTopicsGuidCommentsPostRequest($version, $project_id, $guid, $comment_post);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bcfVersionProjectsProjectIdTopicsGuidCommentsPost'
     *
     * @param  string $version BFC Version (required)
     * @param  string $project_id Project ID (required)
     * @param  string $guid Topic guid (required)
     * @param  \Swagger\Client\Model\CommentPOST $comment_post (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bcfVersionProjectsProjectIdTopicsGuidCommentsPostRequest($version, $project_id, $guid, $comment_post = null)
    {
        // verify the required parameter 'version' is set
        if ($version === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling bcfVersionProjectsProjectIdTopicsGuidCommentsPost'
            );
        }
        // verify the required parameter 'project_id' is set
        if ($project_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling bcfVersionProjectsProjectIdTopicsGuidCommentsPost'
            );
        }
        // verify the required parameter 'guid' is set
        if ($guid === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guid when calling bcfVersionProjectsProjectIdTopicsGuidCommentsPost'
            );
        }

        $resourcePath = '/bcf/{version}/projects/{project_id}/topics/{guid}/comments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }
        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($guid !== null) {
            $resourcePath = str_replace(
                '{' . 'guid' . '}',
                ObjectSerializer::toPathValue($guid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($comment_post)) {
            $_tempBody = $comment_post;
        }

        if ($multipart) {
            $headers= $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
